name: build default on macos

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: configure cmake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      - name: make
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      - name: ctest
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}
